// <auto-generated />
using System;
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    partial class DiscountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Discount.Grpc.Models.Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("ApplicableCategories")
                        .HasColumnType("TEXT");

                    b.Property<string>("AutomaticType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxCumulativeDiscountPercentage")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumPurchaseAmount")
                        .HasColumnType("REAL");

                    b.Property<double>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TierRules")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeValue")
                        .IsUnique();

                    b.ToTable("Codes", (string)null);
                });

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("ApplicableCategories")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("MinimumPurchaseAmount")
                        .HasColumnType("REAL");

                    b.Property<double>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupon", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 0.0,
                            Description = "IPhone X New",
                            MinimumPurchaseAmount = 0.0,
                            Percentage = 30.0,
                            ProductName = "IPhone X",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 0.0,
                            Description = "Samsung 10 New",
                            MinimumPurchaseAmount = 0.0,
                            Percentage = 50.0,
                            ProductName = "Samsung 10",
                            Status = "Active"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
